In [ ]:
%matplotlib inline
import os
import calendar
from pathlib import Path
import numpy as np
import networkx as nx
import pandas as pd
from pandas.plotting import scatter_matrix, parallel_coordinates
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pylab as plt


import statsmodels.formula.api as smf


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [ ]:
#read Default data
Default = pd.read_csv('Default.csv')
#housing_df = pd.read_csv('BostonHousing.csv')
d2=Default

In [ ]:
### WE want to keep the categorical variable and create a dummy variable for that in a seperate column ####

student_dummy=pd.get_dummies(d2['student'])

student_dummy.columns =['student_No', 'student_Yes']
student_dummy.head()

d3=pd.concat([d2,student_dummy], axis=1)
d3.head()

default student      balance       income  student_No  student_Yes
0      No      No   729.526495  44361.62507           1            0
1      No     Yes   817.180407  12106.13470           0            1
2      No      No  1073.549164  31767.13895           1            0
3      No      No   529.250605  35704.49394           1            0
4      No      No   785.655883  38463.49588           1            0

In [ ]:
### creating dummy variable for default ######################################

default_dummy=pd.get_dummies(d2['default'])

default_dummy.columns =['default_No', 'default_Yes']
default_dummy.head()

d4=pd.concat([d3,default_dummy], axis=1)
d4.head()

default student      balance       income  student_No  student_Yes  \
0      No      No   729.526495  44361.62507           1            0   
1      No     Yes   817.180407  12106.13470           0            1   
2      No      No  1073.549164  31767.13895           1            0   
3      No      No   529.250605  35704.49394           1            0   
4      No      No   785.655883  38463.49588           1            0   

   default_No  default_Yes  
0           1            0  
1           1            0  
2           1            0  
3           1            0  
4           1            0

In [ ]:

X = d4[['balance', 'income', 'student_Yes']].values
y = d4['default_Yes'].values.reshape(-1,1)

#Prior to training our model, we’ll set aside a portion of our data in order to evaluate its performance.

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
X.shape

(10000, 3)

In [ ]:
X_train

array([[7.80172569e+02, 5.16568741e+04, 0.00000000e+00],
       [1.05137689e+03, 1.32714647e+04, 1.00000000e+00],
       [1.40587665e+03, 2.70713225e+04, 1.00000000e+00],
       ...,
       [1.23447648e+03, 3.13133746e+04, 0.00000000e+00],
       [0.00000000e+00, 2.93226314e+04, 0.00000000e+00],
       [9.64820253e+02, 3.43907460e+04, 0.00000000e+00]])

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, classification_report

# Train LDA model
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

# Predict on test data
y_pred_lda = lda.predict(X_test)

# Evaluate performance
lda_acc = accuracy_score(y_test, y_pred_lda)
lda_report = classification_report(y_test, y_pred_lda)

print("LDA Accuracy:", lda_acc)
print("LDA Classification Report:\n", lda_report)

LDA Accuracy: 0.9748
LDA Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      2421
           1       0.79      0.28      0.41        79

    accuracy                           0.97      2500
   macro avg       0.88      0.64      0.70      2500
weighted avg       0.97      0.97      0.97      2500



C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [ ]:
from sklearn.linear_model import LogisticRegression

# Initialize and train Logistic Regression model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predict on test data
y_pred_log = log_reg.predict(X_test)

# Evaluate model
print("Logistic Regression Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("Classification Report:\n", classification_report(y_test, y_pred_log))

Logistic Regression Performance:
Accuracy: 0.9684
Confusion Matrix:
 [[2421    0]
 [  79    0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98      2421
           1       0.00      0.00      0.00        79

    accuracy                           0.97      2500
   macro avg       0.48      0.50      0.49      2500
weighted avg       0.94      0.97      0.95      2500



C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Initialize and train LDA model
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LinearDiscriminantAnalysis()

In [ ]:
# Predict on test data
y_pred_lda = lda.predict(X_test)

# Evaluate model
print("LDA Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred_lda))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lda))
print("Classification Report:\n", classification_report(y_test, y_pred_lda))

LDA Performance:
Accuracy: 0.9748
Confusion Matrix:
 [[2415    6]
 [  57   22]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      2421
           1       0.79      0.28      0.41        79

    accuracy                           0.97      2500
   macro avg       0.88      0.64      0.70      2500
weighted avg       0.97      0.97      0.97      2500



In [ ]:
from sklearn.naive_bayes import GaussianNB

# Initialize and train Naive Bayes model
nb = GaussianNB()
nb.fit(X_train, y_train)

C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [ ]:
# Predict on test data
y_pred_nb = nb.predict(X_test)

# Evaluate model
print("Naive Bayes Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))
print("Classification Report:\n", classification_report(y_test, y_pred_nb))

Naive Bayes Performance:
Accuracy: 0.974
Confusion Matrix:
 [[2410   11]
 [  54   25]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      2421
           1       0.69      0.32      0.43        79

    accuracy                           0.97      2500
   macro avg       0.84      0.66      0.71      2500
weighted avg       0.97      0.97      0.97      2500



In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize and train KNN model with 5 neighbors
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

C:\Users\rashraf\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
y_pred_knn = knn.predict(X_test)

# Evaluate model
print("KNN Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))

KNN Performance:
Accuracy: 0.9692
Confusion Matrix:
 [[2406   15]
 [  62   17]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98      2421
           1       0.53      0.22      0.31        79

    accuracy                           0.97      2500
   macro avg       0.75      0.60      0.65      2500
weighted avg       0.96      0.97      0.96      2500



In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Encode categorical variables
df=d4
label_enc = LabelEncoder()
df['default'] = label_enc.fit_transform(df['default'])  # Convert 'No' to 0 and 'Yes' to 1
df['student'] = label_enc.fit_transform(df['student'])  # Convert 'No' to 0 and 'Yes' to 1

# Define features and target variable
X = df[['student', 'balance', 'income']]
y = df['default']

# Split the dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Standardize numerical features
scaler = StandardScaler()
X_train[['balance', 'income']] = scaler.fit_transform(X_train[['balance', 'income']])
X_test[['balance', 'income']] = scaler.transform(X_test[['balance', 'income']])

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "LDA": LinearDiscriminantAnalysis(),
    "Naive Bayes": GaussianNB(),
    "KNN": KNeighborsClassifier(n_neighbors=5)  # Default KNN with 5 neighbors
}

# Train models and evaluate on test set
performance = {}

for name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Store performance metrics
    performance[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Confusion Matrix": confusion_matrix(y_test, y_pred),
        "Classification Report": classification_report(y_test, y_pred, output_dict=True)
    }

# Create comparison dataframe
comparison_data = {
    "Model": ["Logistic Regression", "LDA", "Naive Bayes", "KNN"],
    "Accuracy": [
        performance["Logistic Regression"]["Accuracy"],
        performance["LDA"]["Accuracy"],
        performance["Naive Bayes"]["Accuracy"],
        performance["KNN"]["Accuracy"]
    ],
    "Precision (Default=1)": [
        performance["Logistic Regression"]["Classification Report"]["1"]["precision"],
        performance["LDA"]["Classification Report"]["1"]["precision"],
        performance["Naive Bayes"]["Classification Report"]["1"]["precision"],
        performance["KNN"]["Classification Report"]["1"]["precision"]
    ],
    "Recall (Default=1)": [
        performance["Logistic Regression"]["Classification Report"]["1"]["recall"],
        performance["LDA"]["Classification Report"]["1"]["recall"],
        performance["Naive Bayes"]["Classification Report"]["1"]["recall"],
        performance["KNN"]["Classification Report"]["1"]["recall"]
    ],
    "F1-Score (Default=1)": [
        performance["Logistic Regression"]["Classification Report"]["1"]["f1-score"],
        performance["LDA"]["Classification Report"]["1"]["f1-score"],
        performance["Naive Bayes"]["Classification Report"]["1"]["f1-score"],
        performance["KNN"]["Classification Report"]["1"]["f1-score"]
    ]
}

# Convert to DataFrame
comparison_df = pd.DataFrame(comparison_data)

# Display results
print(comparison_df)  # Print comparison table

                 Model  Accuracy  Precision (Default=1)  Recall (Default=1)  \
0  Logistic Regression     0.973               0.724138            0.313433   
1                  LDA     0.972               0.761905            0.238806   
2          Naive Bayes     0.967               0.512821            0.298507   
3                  KNN     0.968               0.542857            0.283582   

   F1-Score (Default=1)  
0              0.437500  
1              0.363636  
2              0.377358  
3              0.372549  


C:\Users\rashraf\Anaconda3\lib\site-packages\pandas\core\frame.py:3678: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)
C:\Users\rashraf\Anaconda3\lib\site-packages\pandas\core\frame.py:3678: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)
